//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int idFoto { get; set; }
        public int idAnagrafica { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<bool> Principale { get; set; }
    
        public virtual Anagrafica Anagrafica { get; set; }
    }
}
