//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CowBoyEntities : DbContext
    {
        public CowBoyEntities()
            : base("name=CowBoyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anagrafica> Anagrafica { get; set; }
        public virtual DbSet<Foto> Foto { get; set; }
        public virtual DbSet<PartiSalti> PartiSalti { get; set; }
        public virtual DbSet<Salti> Salti { get; set; }
        public virtual DbSet<Stati> Stati { get; set; }
    }
}
