//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartiSalti
    {
        public PartiSalti()
        {
            this.Salti = new HashSet<Salti>();
        }
    
        public int idPartoSalto { get; set; }
        public int idAnagrafica { get; set; }
        public Nullable<System.DateTime> DataMessaAsciutta { get; set; }
        public Nullable<System.DateTime> DataParto { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Naturale { get; set; }
        public Nullable<bool> Facile { get; set; }
        public Nullable<bool> DaSola { get; set; }
        public string PartoNoParto { get; set; }
        public Nullable<bool> Abortito { get; set; }
    
        public virtual Anagrafica Anagrafica { get; set; }
        public virtual ICollection<Salti> Salti { get; set; }
    }
}
