//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CowBoy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaNota
    {
        public PrimaNota()
        {
            this.VociPrimaNota = new HashSet<VociPrimaNota>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Anno { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Numero { get; set; }
        public string Descrizione { get; set; }
        public Nullable<bool> PagIncassata { get; set; }
        public Nullable<int> IdFornitoreCliente { get; set; }
        public Nullable<decimal> Dare { get; set; }
        public Nullable<decimal> Avere { get; set; }
        public Nullable<decimal> ImporotIva { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<VociPrimaNota> VociPrimaNota { get; set; }
    }
}
