//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CowBoy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salti
    {
        public int idSalto { get; set; }
        public int idPartoSalto { get; set; }
        public Nullable<System.DateTime> DataSalto { get; set; }
        public Nullable<int> idToro { get; set; }
        public Nullable<bool> SaltoArtificiale { get; set; }
        public string MatrToroArt { get; set; }
        public string Note { get; set; }
    
        public virtual PartiSalti PartiSalti { get; set; }
        public virtual Anagrafica Anagrafica { get; set; }
    }
}
