//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CowBoy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VociPrimaNota
    {
        public int IdVoce { get; set; }
        public Nullable<int> IdPrimaNota { get; set; }
        public string Descrizione { get; set; }
        public Nullable<decimal> Dare { get; set; }
        public Nullable<decimal> Avere { get; set; }
        public Nullable<decimal> Iva { get; set; }
    
        public virtual PrimaNota PrimaNota { get; set; }
    }
}
